In [1]:
import numpy as np
import pandas as pd

In [2]:
# df = pd.read_csv("ratings_v2000&600.csv")
# ratings_v2000&600
# ratings_v2005&300

In [ ]:
df = pd.read_csv("ratings.csv")

# delete unnecessary column
# df = df.drop("timestamp",axis = 1)

# mini dataset
# df = df[df['userId'] <= 15]
# df = df[df['movieId'] <= 8]
df

In [3]:
# 把rate取0-1
df["rating"] = df["rating"]/5.0

#pivot
movies = df.pivot_table(index=['userId'],columns='movieId',values='rating') # x:movie_id; y:user_id
users = df.pivot_table(index=['movieId'],columns='userId',values='rating') # x:user_id; y:movie_id
n_users, n_movies = movies.shape

df_movies = movies.fillna(0) 
df_users = users.fillna(0)
# df_movies = movies.fillna(0.5) 
# df_users = users.fillna(0.5)

In [ ]:
df_movies

In [ ]:
df_users

In [4]:
userId_list = df_users.columns
movieId_list = df_movies.columns
n_movies = len(movieId_list)
n_users = len(userId_list)
movieId_list, userId_list,n_movies, n_users

(Int64Index([  2769,   3177,   3190,   3225,   3273,   3275,   3276,   3285,
               3286,   3287,
             ...
             191005, 193565, 193567, 193571, 193573, 193579, 193581, 193583,
             193585, 193587],
            dtype='int64', name='movieId', length=4603),
 Int64Index([  1,   2,   3,   4,   7,   9,  10,  12,  13,  15,
             ...
             585, 586, 590, 591, 593, 594, 596, 598, 599, 600],
            dtype='int64', name='userId', length=436),
 4603,
 436)

In [8]:
# create a empty similarity_matrix_icf
similarity_matrix_icf = pd.DataFrame(data = np.zeros((n_movies,n_movies)), index = movieId_list, columns = movieId_list)

for movie_id in movieId_list:
    for other_movie_id in movieId_list:
        
        vec_movie = []
        vec_other_movie_id = []

        if movie_id != other_movie_id:
            
            for user_id in userId_list:

                this = df_users[user_id]
                vec_movie.append(this[movie_id])
                vec_other_movie_id.append(this[other_movie_id])
            
            similarity_matrix_icf[movie_id][other_movie_id] = np.corrcoef(np.array(vec_movie), np.array(vec_other_movie_id))[0][1]

# CSV
# similarity_matrix_icf.to_csv("similarity_matrix_v2000&600_icf.csv",header=True, sep = ',')
similarity_matrix_icf

movieId,2769,3177,3190,3225,3273,3275,3276,3285,3286,3287,...,191005,193565,193567,193571,193573,193579,193581,193583,193585,193587
movieId,,,,,,,,,,,,,,,,,,,,,
2769,0.000000,-0.011531,-0.008319,0.103194,0.078868,0.100696,0.244764,0.115725,0.075890,-0.007910,...,-0.004867,-0.004867,-0.004867,-0.004867,-0.004867,-0.004867,-0.004867,-0.004867,-0.004867,-0.004867
3177,-0.011531,0.000000,-0.009311,-0.009769,0.346316,0.166491,-0.005447,0.186482,0.234038,-0.008853,...,-0.005447,-0.005447,-0.005447,-0.005447,-0.005447,-0.005447,-0.005447,-0.005447,-0.005447,-0.005447
3190,-0.008319,-0.009311,0.000000,0.281010,0.010446,0.057505,-0.003930,-0.020694,-0.008117,-0.006387,...,-0.003930,-0.003930,-0.003930,-0.003930,-0.003930,-0.003930,-0.003930,-0.003930,-0.003930,-0.003930
3225,0.103194,-0.009769,0.281010,0.000000,0.118161,0.132421,-0.004123,0.016458,0.030162,-0.006701,...,-0.004123,-0.004123,-0.004123,-0.004123,-0.004123,-0.004123,-0.004123,-0.004123,-0.004123,-0.004123
3273,0.078868,0.346316,0.010446,0.118161,0.000000,0.086836,-0.010968,0.178211,0.083182,-0.017826,...,-0.010968,-0.010968,-0.010968,-0.010968,-0.010968,-0.010968,-0.010968,-0.010968,-0.010968,-0.010968
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193579,-0.004867,-0.005447,-0.003930,-0.004123,-0.010968,-0.015489,-0.002299,-0.012106,-0.004749,-0.003736,...,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000
193581,-0.004867,-0.005447,-0.003930,-0.004123,-0.010968,-0.015489,-0.002299,-0.012106,-0.004749,-0.003736,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000
193583,-0.004867,-0.005447,-0.003930,-0.004123,-0.010968,-0.015489,-0.002299,-0.012106,-0.004749,-0.003736,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,1.000000
193585,-0.004867,-0.005447,-0.003930,-0.004123,-0.010968,-0.015489,-0.002299,-0.012106,-0.004749,-0.003736,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000
193587,-0.004867,-0.005447,-0.003930,-0.004123,-0.010968,-0.015489,-0.002299,-0.012106,-0.004749,-0.003736,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000

In [9]:
# 跟mid最像的100个movies
col_name = []
for i in range(1,101): # (1,101)
    col_name.append('m_id'+str(i))
n_col = len(col_name)
ll_similar_movies = pd.DataFrame(data = np.zeros((n_movies,len(col_name))), index = movieId_list, columns = col_name)
for mid in movieId_list:
    line = similarity_matrix_icf[mid].sort_values(ascending=False).index.tolist()[:n_col]
    for j in range(n_col):
        ll_similar_movies[col_name[j]][mid] = line[j]
        
# ll_similar_movies.to_csv("ll_similar_movies_100_v2000&600.csv",header=True, sep = ',')
ll_similar_movies

,m_id1,m_id2,m_id3,m_id4,m_id5,m_id6,m_id7,m_id8,m_id9,m_id10,...,m_id91,m_id92,m_id93,m_id94,m_id95,m_id96,m_id97,m_id98,m_id99,m_id100
movieId,,,,,,,,,,,,,,,,,,,,,
2769,3858.0,45062.0,4268.0,4866.0,80126.0,4055.0,4450.0,3862.0,5486.0,4735.0,...,4147.0,5071.0,5083.0,60128.0,5636.0,50792.0,5347.0,3910.0,4168.0,5680.0
3177,42725.0,59143.0,34530.0,4989.0,47640.0,5942.0,5874.0,74532.0,44840.0,48520.0,...,183959.0,165671.0,118930.0,159161.0,119153.0,100194.0,162602.0,162344.0,123200.0,161024.0
3190,3316.0,3454.0,67193.0,45648.0,137345.0,95717.0,46574.0,6882.0,97230.0,135787.0,...,78959.0,58306.0,73808.0,74696.0,159061.0,77709.0,59016.0,5268.0,77201.0,163809.0
3225,5324.0,3898.0,3324.0,6280.0,7175.0,8782.0,5787.0,4743.0,4453.0,5675.0,...,4974.0,31221.0,7263.0,34338.0,5267.0,3190.0,37830.0,40583.0,6686.0,6367.0
3273,3617.0,46974.0,3177.0,34153.0,52967.0,8943.0,6898.0,5685.0,6269.0,6547.0,...,7326.0,6965.0,5525.0,7177.0,8938.0,8813.0,7382.0,6400.0,31903.0,35015.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193579,193587.0,162982.0,175585.0,161594.0,174479.0,158035.0,177285.0,178111.0,180987.0,165635.0,...,108932.0,84152.0,6283.0,122892.0,5388.0,119145.0,122900.0,136864.0,114662.0,102125.0
193581,193587.0,162982.0,175585.0,161594.0,174479.0,158035.0,177285.0,178111.0,180987.0,165635.0,...,108932.0,84152.0,6283.0,122892.0,5388.0,119145.0,122900.0,136864.0,114662.0,102125.0
193583,193587.0,162982.0,175585.0,161594.0,174479.0,158035.0,177285.0,178111.0,180987.0,165635.0,...,108932.0,84152.0,6283.0,122892.0,5388.0,119145.0,122900.0,136864.0,114662.0,102125.0
193585,193587.0,162982.0,175585.0,161594.0,174479.0,158035.0,177285.0,178111.0,180987.0,165635.0,...,108932.0,84152.0,6283.0,122892.0,5388.0,119145.0,122900.0,136864.0,114662.0,102125.0
193587,157369.0,148978.0,161594.0,175475.0,165635.0,158035.0,177285.0,178111.0,168090.0,170907.0,...,108932.0,84152.0,6283.0,122892.0,5388.0,119145.0,122900.0,136864.0,114662.0,102125.0

In [5]:
# Compute similarity_matrix_ucf

# create a empty similarity_matrix_ucf
similarity_matrix_ucf = pd.DataFrame(data = np.zeros((n_users,n_users)), index = userId_list, columns = userId_list)

for user_id in userId_list:
    for other_user_id in userId_list:
        vec_user = []
        vec_other_user_id = []
        
        if user_id != other_user_id:
            
            for movie_id in movieId_list:
                
                this = df_movies[movie_id]
                vec_user.append(this[user_id])
                vec_other_user_id.append(this[other_user_id])
                    
            similarity_matrix_ucf[user_id][other_user_id] = np.corrcoef(np.array(vec_user), np.array(vec_other_user_id))[0][1]

# CSV
# similarity_matrix_ucf.to_csv("similarity_matrix_v2000&600_ucf.csv",header=True, sep = ',')
similarity_matrix_ucf

userId,1,2,3,4,7,9,10,12,13,15,...,585,586,590,591,593,594,596,598,599,600
userId,,,,,,,,,,,,,,,,,,,,,
1,0.000000,0.088314,-0.000837,-0.002644,0.080484,-0.001683,0.041608,-0.001276,0.264369,0.089892,...,-0.002399,0.081647,0.071209,0.327798,0.180043,0.153757,0.046356,-0.001979,0.047186,0.035098
2,0.088314,0.000000,-0.001889,-0.005964,0.034013,-0.003797,0.066569,-0.002880,0.052875,0.128709,...,0.204517,0.069068,0.080739,0.067291,0.037998,0.023392,0.102444,0.045417,0.130394,0.028172
3,-0.000837,-0.001889,0.000000,-0.002059,-0.003413,-0.001311,-0.004064,-0.000994,-0.001566,0.064822,...,-0.001868,-0.004585,-0.005590,-0.001282,-0.002188,-0.002430,-0.006373,-0.001541,0.023959,0.047085
4,-0.002644,-0.005964,-0.002059,0.000000,0.052072,-0.004139,0.006085,0.072729,0.102652,-0.004826,...,0.048205,-0.014475,0.061508,0.099452,0.140809,-0.001334,0.053837,0.000328,0.064919,0.130718
7,0.080484,0.034013,-0.003413,0.052072,0.000000,0.162902,0.126690,0.040232,0.054448,0.179233,...,0.043359,0.153866,0.337523,0.137175,0.300927,0.058436,0.220135,0.068133,0.146566,0.234990
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
594,0.153757,0.023392,-0.002430,-0.001334,0.058436,-0.004884,0.157596,0.097078,0.083496,0.011434,...,-0.006960,0.038693,0.093524,0.105705,0.065433,0.000000,0.025377,-0.005742,0.015653,0.052713
596,0.046356,0.102444,-0.006373,0.053837,0.220135,0.091703,0.135767,0.059109,0.084271,0.287185,...,0.085256,0.330462,0.302444,0.070387,0.179620,0.025377,0.000000,0.071456,0.267826,0.178708
598,-0.001979,0.045417,-0.001541,0.000328,0.068133,-0.003098,0.022573,-0.002349,-0.003702,0.036009,...,0.042708,0.044020,0.098824,-0.003029,0.057652,-0.005742,0.071456,0.000000,0.045826,0.090152
599,0.047186,0.130394,0.023959,0.064919,0.146566,0.054947,0.060476,-0.018161,0.104431,0.187648,...,0.115605,0.135913,0.258043,0.058382,0.159059,0.015653,0.267826,0.045826,0.000000,0.207405
600,0.035098,0.028172,0.047085,0.130718,0.234990,0.151426,0.130371,0.036276,0.065416,0.151565,...,0.045913,0.049018,0.270474,0.065344,0.223821,0.052713,0.178708,0.090152,0.207405,0.000000

In [6]:
# User_Based CF user * movie similarity matrix
avg = np.mean(df_movies, axis = 1) # each user's avg rate
sum_similarity_uid = np.sum(similarity_matrix_ucf,axis = 1) # sum[S(uid,otheruid) while otheruid in userId_list]
df_users_mean = df_users - avg

core_similarity_ucf = pd.DataFrame(data = np.zeros((n_users,n_movies)), index = userId_list, columns = movieId_list)
for mid in movieId_list:
    for uid in userId_list:
        avg_uid = avg[uid]       
        up = np.sum(df_users_mean.T[mid]*similarity_matrix_ucf[uid])
        down = sum_similarity_uid[uid]
        res = avg_uid + up/down
        core_similarity_ucf[mid][uid] = res
        
# core_similarity_ucf.to_csv("core_similarity_ucf_v2000&600.csv",header=True, sep = ',')
core_similarity_ucf

movieId,2769,3177,3190,3225,3273,3275,3276,3285,3286,3287,...,191005,193565,193567,193571,193573,193579,193581,193583,193585,193587
userId,,,,,,,,,,,,,,,,,,,,,
1,-0.002729,0.005264,-0.006041,0.001532,0.076452,0.072538,-0.009983,0.043682,0.009149,0.002119,...,-0.008934,-0.009233,-0.009531,-0.009233,-0.009233,-0.009233,-0.009233,-0.009233,-0.009233,-0.009233
2,-0.008615,-0.003598,-0.011497,-0.011764,0.015618,0.112719,-0.012692,0.044673,-0.007873,-0.012486,...,-0.009915,-0.010643,-0.011371,-0.010643,-0.010643,-0.010643,-0.010643,-0.010643,-0.010643,-0.010643
3,-0.013453,-0.002518,-0.017320,-0.019006,0.008558,0.113764,-0.017590,0.050779,-0.013300,-0.019379,...,-0.019183,-0.019042,-0.018900,-0.019042,-0.019042,-0.019042,-0.019042,-0.019042,-0.019042,-0.019042
4,0.015613,0.005656,-0.004732,-0.006627,0.028927,0.103342,-0.009902,0.036424,-0.008851,-0.004215,...,-0.009414,-0.009564,-0.009715,-0.009564,-0.009564,-0.009564,-0.009564,-0.009564,-0.009564,-0.009564
7,0.002944,0.004739,-0.002435,-0.000810,0.029174,0.152614,-0.005547,0.044331,-0.000971,0.000800,...,-0.005853,-0.005899,-0.005946,-0.005899,-0.005899,-0.005899,-0.005899,-0.005899,-0.005899,-0.005899
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
594,0.003900,0.012452,-0.004822,0.004449,0.050632,0.113680,-0.008116,0.047588,0.002251,0.010298,...,-0.008490,-0.008466,-0.008443,-0.008466,-0.008466,-0.008466,-0.008466,-0.008466,-0.008466,-0.008466
596,0.032850,0.033895,0.027761,0.028335,0.054838,0.168546,0.025507,0.076843,0.029055,0.028131,...,0.027922,0.027298,0.026673,0.027298,0.027298,0.027298,0.027298,0.027298,0.027298,0.027298
598,-0.011977,-0.006936,-0.013830,-0.013187,0.005361,0.119139,-0.014767,0.027864,-0.012405,-0.012351,...,-0.013192,-0.013548,-0.013904,-0.013548,-0.013548,-0.013548,-0.013548,-0.013548,-0.013548,-0.013548
599,0.099406,0.101677,0.090183,0.093423,0.127257,0.257783,0.089221,0.155017,0.094291,0.091557,...,0.090977,0.090475,0.089974,0.090475,0.090475,0.090475,0.090475,0.090475,0.090475,0.090475
600,0.015227,0.018732,0.008876,0.010043,0.039571,0.151871,0.005961,0.060986,0.009392,0.010203,...,0.005840,0.005784,0.005728,0.005784,0.005784,0.005784,0.005784,0.005784,0.005784,0.005784

In [7]:
# User_Based CF recommend

col_name = []
for i in range(1,101): 
    col_name.append('m_id'+str(i))
n_col = len(col_name)

recommend_table = pd.DataFrame(data = np.zeros((n_users,len(col_name))), index = userId_list, columns = col_name)
core_similarity_ucf_T = core_similarity_ucf.T

for uid in userId_list:
    line = core_similarity_ucf_T[uid].sort_values(ascending=False).index.tolist()[:n_col]
    for j in range(n_col):
        recommend_table[col_name[j]][uid] = line[j]

# recommend_table.to_csv("recommend_table_v2000&600.csv",header=True, sep = ',')
recommend_table

,m_id1,m_id2,m_id3,m_id4,m_id5,m_id6,m_id7,m_id8,m_id9,m_id10,...,m_id91,m_id92,m_id93,m_id94,m_id95,m_id96,m_id97,m_id98,m_id99,m_id100
userId,,,,,,,,,,,,,,,,,,,,,
1,3578.0,3793.0,4993.0,3996.0,4306.0,7153.0,5952.0,4226.0,6539.0,58559.0,...,74458.0,6378.0,51255.0,33679.0,3785.0,4370.0,5669.0,40815.0,7147.0,50872.0
2,58559.0,79132.0,4993.0,7153.0,3578.0,5952.0,48516.0,4226.0,6874.0,68157.0,...,122886.0,33493.0,3948.0,40815.0,56174.0,3535.0,8636.0,57669.0,88125.0,69844.0
3,3949.0,4226.0,7361.0,6874.0,4878.0,4993.0,58559.0,48516.0,4995.0,79132.0,...,134130.0,80463.0,5218.0,78499.0,5669.0,3863.0,6365.0,64614.0,5378.0,106782.0
4,4226.0,3996.0,4993.0,4306.0,3578.0,5952.0,4973.0,3897.0,4034.0,4027.0,...,6218.0,6863.0,33493.0,68157.0,51662.0,68954.0,4816.0,55820.0,45722.0,8949.0
7,4993.0,5952.0,7153.0,4306.0,6539.0,3578.0,4226.0,6377.0,8961.0,4886.0,...,34405.0,3753.0,5669.0,4246.0,3275.0,34162.0,55820.0,56174.0,6502.0,48385.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
594,3578.0,3793.0,4306.0,4993.0,5952.0,6377.0,7153.0,6539.0,5349.0,4886.0,...,8644.0,4816.0,50872.0,4979.0,54286.0,41566.0,3911.0,3949.0,8641.0,5459.0
596,4993.0,7153.0,5952.0,58559.0,4306.0,4226.0,3578.0,79132.0,6539.0,6377.0,...,6016.0,96079.0,55820.0,4979.0,6863.0,71535.0,88125.0,6373.0,81845.0,53125.0
598,4993.0,7153.0,5952.0,7361.0,4226.0,58559.0,79132.0,4306.0,6377.0,6539.0,...,80463.0,6373.0,68358.0,56174.0,78499.0,4246.0,81834.0,3751.0,4979.0,4034.0
599,4993.0,7153.0,5952.0,4226.0,58559.0,3578.0,4306.0,6874.0,6539.0,79132.0,...,112852.0,6863.0,54503.0,56174.0,8641.0,48385.0,6378.0,6373.0,3275.0,34405.0
600,4993.0,5952.0,7153.0,4226.0,4306.0,6539.0,7361.0,3578.0,6874.0,6377.0,...,6378.0,48385.0,33166.0,3535.0,8641.0,6373.0,4720.0,5991.0,4447.0,8644.0

In [ ]:
# 每个user打满分的电影后20个
col_name = []
for i in range(1,21): # (1,101)
    col_name.append('m_id'+str(i))
user_like_list = pd.DataFrame(data = np.zeros((n_users,20)), index = userId_list, columns = col_name)

for uid in userId_list:
    this = ratings_df[ratings_df['userId'] == uid]
    this = this[this['rating'] == 1]
    this = this.sort_values(by=['movieId'], ascending=False)[:20]['movieId'].tolist()
    for j in range(len(this)):
        user_like_list[col_name[j]][uid] = this[j]

# user_like_list.to_csv("user_like_list_20_v2005&300.csv",header=True, sep = ',')
user_like_list

In [ ]:
# 跟uid最像的20个用户
col_name = []
for i in range(1,21): 
    col_name.append('u_id'+str(i))
n_col = len(col_name)

ll_similar_users = pd.DataFrame(data = np.zeros((n_users,len(col_name))), index = userId_list, columns = col_name)

for uid in userId_list:
    line = similarity_matrix_ucf[uid].sort_values(ascending=False).index.tolist()[:n_col]
    for j in range(n_col):
        ll_similar_users[col_name[j]][uid] = line[j]
        
# ll_similar_users.to_csv("ll_similar_users_100_v2005&300.csv",header=True, sep = ',')
ll_similar_users

In [ ]:
# 以下为新用户推荐

In [ ]:
from lib2to3.pgen2.token import RARROW
from sqlalchemy import create_engine

endpoint = 'll-db-instance.ckrv0jhnsibp.us-east-1.rds.amazonaws.com'
username = 'admin'
password = 'yl8735yl8735'
database_name = 'LL_REC'

def mysql_reader():
    engine = create_engine("mysql+pymysql://{}:{}@{}/{}?charset={}".format(username, password, endpoint, database_name,'utf8'),pool_pre_ping=True)
    con = engine.connect()  #创建连接
    df = pd.read_sql_table(table_name='ll_ratings_temp', con=con)
    con.close()
    return df

df_new = mysql_reader()

In [ ]:
df_new = df_new.rename(columns={'user_id': 'userId', 'movie_id': 'movieId'})

In [ ]:
df_res = pd.concat([df,df_new], axis = 0)
df_res

In [ ]:
# 把rate取0-1
df_res["rating"] = df_res["rating"]/5.0

#pivot
movies = df_res.pivot_table(index=['userId'],columns='movieId',values='rating') # x:movie_id; y:user_id
users = df_res.pivot_table(index=['movieId'],columns='userId',values='rating') # x:user_id; y:movie_id
n_users, n_movies = movies.shape

df_movies = movies.fillna(0) 
df_users = users.fillna(0)
# df_movies = movies.fillna(0.5) 
# df_users = users.fillna(0.5)

userId_list = df_users.columns
movieId_list = df_movies.columns

n_movies = len(movieId_list)
n_users = len(userId_list)

movieId_list, userId_list,n_movies, n_users

In [ ]:
# Compute similarity_matrix_ucf

new_user_id = 1001 #############################################

new_similarity_matrix_ucf = pd.DataFrame(data = np.zeros((n_users,n_users)), index = userId_list, columns = userId_list)

user_id = new_user_id
for other_user_id in userId_list:
    vec_user = []
    vec_other_user_id = []

    if user_id != other_user_id:

        for movie_id in movieId_list:

            this = df_movies[movie_id]
            vec_user.append(this[user_id])
            vec_other_user_id.append(this[other_user_id])
        new_similarity_matrix_ucf[new_user_id][other_user_id] = np.corrcoef(np.array(vec_user), np.array(vec_other_user_id))[0][1]

# CSV
# similarity_matrix_ucf.to_csv("similarity_matrix_v2005&300_ucf.csv",header=True, sep = ',')
new_similarity_matrix_ucf[new_user_id]

In [ ]:
# similarity_matrix_ucf = pd.read_csv("similarity_matrix_v2005&300_ucf.csv",index_col=0)

In [ ]:
# create a new similarity_matrix_ucf
similarity_matrix_ucf = pd.concat([similarity_matrix_ucf,new_similarity_matrix_ucf[user_id]], axis = 1)
similarity_matrix_ucf.iloc[-1] = new_similarity_matrix_ucf[user_id]
similarity_matrix_ucf

In [ ]:
# then compute core_similarity_ucf and recommend table

# User_Based CF user * movie similarity matrix
avg = np.mean(df_movies, axis = 1) # each user's avg rate
sum_similarity_uid = np.sum(similarity_matrix_ucf,axis = 1) # sum[S(uid,otheruid) while otheruid in userId_list]
df_users_mean = df_users - avg



core_similarity_ucf = pd.DataFrame(data = np.zeros((n_users,n_movies)), index = userId_list, columns = movieId_list)

for mid in movieId_list:
    for uid in userId_list:
        avg_uid = avg[uid]       
        up = np.sum(df_users_mean.T[mid]*similarity_matrix_ucf[uid])
        down = sum_similarity_uid[uid]
        res = avg_uid + up/down
        core_similarity_ucf[mid][uid] = res
        
core_similarity_ucf

In [ ]:
# User_Based CF recommend

col_name = []
for i in range(1,101): 
    col_name.append('m_id'+str(i))
n_col = len(col_name)

recommend_table = pd.DataFrame(data = np.zeros((n_users,len(col_name))), index = userId_list, columns = col_name)
core_similarity_ucf_T = core_similarity_ucf.T

# for uid in userId_list:
uid = new_user_id
line = core_similarity_ucf_T[uid].sort_values(ascending=False).index.tolist()[:n_col]
for j in range(n_col):
    recommend_table[col_name[j]][uid] = line[j]

recommend_table.iloc[-1] # 针对new_user_id的推荐

In [ ]:
# Lambda v1
import numpy as np
import pandas as pd
from lib2to3.pgen2.token import RARROW
import pymysql

endpoint = 'll-db-instance.ckrv0jhnsibp.us-east-1.rds.amazonaws.com'
username = 'admin'
password = 'yl8735yl8735'
database_name = 'LL_REC'

connection = pymysql.connect(host= endpoint,user=username,passwd=password,db=database_name)

def solution():

    cursor = connection.cursor()
    # new_user_id = event['user_id']
    new_user_id = 1001

    cursor.execute('SELECT * FROM ll_ratings where user_id = "'+ str(new_user_id) +'";')
    row = cursor.fetchall()
    df_new = pd.DataFrame(row,columns = ['userId','movieId','rating'])
    df_new.reset_index(drop=True)
    
    if len(df_new) == 0:
        return 'This user has no rating yet........'

    
    df = pd.read_csv("ratings_v2005&300.csv")
    df_new = df_new.rename(columns={'user_id': 'userId', 'movie_id': 'movieId'}) 
    df_res = pd.concat([df,df_new], axis = 0)

    df_res["rating"] = df_res["rating"]/5.0

    #pivot
    movies = df_res.pivot_table(index=['userId'],columns='movieId',values='rating') # x:movie_id; y:user_id
    users = df_res.pivot_table(index=['movieId'],columns='userId',values='rating') # x:user_id; y:movie_id
    
    df_movies = movies.fillna(0) 
    df_users = users.fillna(0)

    userId_list = df_users.columns
    movieId_list = df_movies.columns

    n_movies = len(movieId_list)
    n_users = len(userId_list)
    
    print("load dataset finished, start to compute...")

    # Compute similarity_matrix_ucf
    new_similarity_matrix_ucf = pd.DataFrame(data = np.zeros((n_users,n_users)), index = userId_list, columns = userId_list)
    user_id = new_user_id
    for other_user_id in userId_list:
        vec_user = []
        vec_other_user_id = []
        if user_id != other_user_id:
            for movie_id in movieId_list:
                this = df_movies[movie_id]
                vec_user.append(this[user_id])
                vec_other_user_id.append(this[other_user_id])
            new_similarity_matrix_ucf[new_user_id][other_user_id] = np.corrcoef(np.array(vec_user), np.array(vec_other_user_id))[0][1]

    similarity_matrix_ucf = pd.read_csv("similarity_matrix_v2005&300_ucf.csv", index_col=0)

    # create a new similarity_matrix_ucf
    similarity_matrix_ucf = pd.concat([similarity_matrix_ucf,new_similarity_matrix_ucf[user_id]], axis = 1)
    similarity_matrix_ucf.iloc[-1] = new_similarity_matrix_ucf[user_id]
    # change column name type to string
    similarity_matrix_ucf.columns = similarity_matrix_ucf.columns.astype(str)
    print("new similarity_matrix_ucf finished...")
    
    
    # User_Based CF user * movie similarity matrix
    avg = np.mean(df_movies, axis = 1) # each user's avg rate
    sum_similarity_uid = np.sum(similarity_matrix_ucf,axis = 1) # sum[S(uid,otheruid) while otheruid in userId_list]
    df_users_mean = df_users - avg

    core_similarity_ucf = pd.DataFrame(data = np.zeros((n_users,n_movies)), index = userId_list, columns = movieId_list)
    for mid in movieId_list:
        for uid in userId_list:
            avg_uid = avg[uid]       
            up = np.sum(df_users_mean.T[mid]*similarity_matrix_ucf[str(uid)])
            down = sum_similarity_uid[uid]
            res = avg_uid + up/down
            core_similarity_ucf[mid][uid] = res
    print("core_similarity_ucf finished...")


    # User_Based CF recommend
    col_name = []
    for i in range(1,101): 
        col_name.append('m_id'+str(i))
    n_col = len(col_name)

    recommend_table = pd.DataFrame(data = np.zeros((n_users,len(col_name))), index = userId_list, columns = col_name)
    core_similarity_ucf_T = core_similarity_ucf.T

    # for uid in userId_list:
    uid = new_user_id
    line = core_similarity_ucf_T[uid].sort_values(ascending=False).index.tolist()[:n_col]
    for j in range(n_col):
        recommend_table[col_name[j]][uid] = line[j]
    line = recommend_table.iloc[-1] # 针对new_user_id的推荐
    print("recommender line to new_user_id finished...")


    # database update for new_user_id
    sql = 'UPDATE ll_recommender SET m_id1="'+str(line[0])+'"'
    for i in range(1,len(line)):
        sql += ', m_id'+str(i+1)+'="'+str(line[i])+'"'
    sql += ' where userId="'+str(new_user_id)+'";'
    cursor.execute(sql)     
    cursor.execute('COMMIT;')
    print("update database finished...")
    

solution()

In [ ]:
# Lambda v2
# core: fix uid as new_user_id
import numpy as np
import pandas as pd
from lib2to3.pgen2.token import RARROW
import pymysql

endpoint = 'll-db-instance.ckrv0jhnsibp.us-east-1.rds.amazonaws.com'
username = 'admin'
password = 'yl8735yl8735'
database_name = 'LL_REC'

connection = pymysql.connect(host= endpoint,user=username,passwd=password,db=database_name)

def solution():

    cursor = connection.cursor()
    # new_user_id = event['user_id']
    new_user_id = 1001

    cursor.execute('SELECT * FROM ll_ratings_temp where user_id = "'+ str(new_user_id) +'";')
    row = cursor.fetchall()
    df_new = pd.DataFrame(row,columns = ['userId','movieId','rating'])
    df_new.reset_index(drop=True)
    
    if len(df_new) == 0:
        return 'This user has no rating yet........'

    
    df = pd.read_csv("ratings_v2005&300.csv")
    df_new = df_new.rename(columns={'user_id': 'userId', 'movie_id': 'movieId'}) 
    df_res = pd.concat([df,df_new], axis = 0)

    df_res["rating"] = df_res["rating"]/5.0

    #pivot
    movies = df_res.pivot_table(index=['userId'],columns='movieId',values='rating') # x:movie_id; y:user_id
    users = df_res.pivot_table(index=['movieId'],columns='userId',values='rating') # x:user_id; y:movie_id
    
    df_movies = movies.fillna(0) 
    df_users = users.fillna(0)

    userId_list = df_users.columns
    movieId_list = df_movies.columns

    n_movies = len(movieId_list)
    n_users = len(userId_list)
    
    print("load dataset finished, start to compute...")

    # Compute similarity_matrix_ucf
    new_similarity_matrix_ucf = pd.DataFrame(data = np.zeros((n_users,n_users)), index = userId_list, columns = userId_list)
    user_id = new_user_id
    for other_user_id in userId_list:
        vec_user = []
        vec_other_user_id = []
        if user_id != other_user_id:
            for movie_id in movieId_list:
                this = df_movies[movie_id]
                vec_user.append(this[user_id])
                vec_other_user_id.append(this[other_user_id])
            new_similarity_matrix_ucf[new_user_id][other_user_id] = np.corrcoef(np.array(vec_user), np.array(vec_other_user_id))[0][1]

    similarity_matrix_ucf = pd.read_csv("similarity_matrix_v2005&300_ucf.csv", index_col=0)

    # create a new similarity_matrix_ucf
    similarity_matrix_ucf = pd.concat([similarity_matrix_ucf,new_similarity_matrix_ucf[user_id]], axis = 1)
    similarity_matrix_ucf.iloc[-1] = new_similarity_matrix_ucf[user_id]
    # change column name type to string
    similarity_matrix_ucf.columns = similarity_matrix_ucf.columns.astype(str)
    print("new similarity_matrix_ucf finished...")
    
    
    # User_Based CF user * movie similarity matrix
    avg = np.mean(df_movies, axis = 1) # each user's avg rate
    sum_similarity_uid = np.sum(similarity_matrix_ucf,axis = 1) # sum[S(uid,otheruid) while otheruid in userId_list]
    df_users_mean = df_users - avg

    core_similarity_ucf = pd.DataFrame(data = np.zeros((n_users,n_movies)), index = userId_list, columns = movieId_list)
    uid = new_user_id
    for mid in movieId_list:
        avg_uid = avg[uid]       
        up = np.sum(df_users_mean.T[mid]*similarity_matrix_ucf[str(uid)])
        down = sum_similarity_uid[uid]
        res = avg_uid + up/down
        core_similarity_ucf[mid][uid] = res
    print("core_similarity_ucf finished...")


    # User_Based CF recommend
    col_name = []
    for i in range(1,101): 
        col_name.append('m_id'+str(i))
    n_col = len(col_name)

    recommend_table = pd.DataFrame(data = np.zeros((n_users,len(col_name))), index = userId_list, columns = col_name)
    core_similarity_ucf_T = core_similarity_ucf.T

    uid = new_user_id
    line = core_similarity_ucf_T[uid].sort_values(ascending=False).index.tolist()[:n_col]
    for j in range(n_col):
        recommend_table[col_name[j]][uid] = line[j]
    line = recommend_table.iloc[-1] # 针对new_user_id的推荐
    print("recommender line to new_user_id finished...")

    return line.tolist()

solution()